-   id: liccheck-poetry
    name: Run liccheck for projects using poetry
    description: Creates a temporary requirements.txt and uses this to run liccheck.
    entry: liccheck-poetry
    files: poetry.lock
    language: python

-   id: import-linter
    name: Run import linter
    description: Checks if python imports are valid.
    entry: import-linter
    types: [file, python]
    language: python
