-   id: liccheck-pipenv
    name: Run liccheck for projects using pipenv
    description: Creates a temporary requirements.txt and uses this to run liccheck.
    entry: liccheck-pipenv
    files: Pipfile.lock
    language: python

-   id: import-linter
    name: Run import linter
    description: Checks if python imports are valid.
    entry: import-linter
    types: [file, python]
    language: python
